source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Alamofire使用' do
#pod 'Alamofire', '~> 4.0'
#pod 'AlamofireSwiftyJSON'
#pod 'SwiftyJSON'
pod 'SnapKit', '~> 3.0.2'
end
